# -*- coding: utf-8 -*-
"""accident_hotspot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1te3eVNlTzTjGCwdmnBvIXWHvgXY7tK3E
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import folium
from folium.plugins import MarkerCluster

df = pd.read_csv('/content/crashing.csv')

df

df.head()

df.tail()

df.shape

df.columns

df.dtypes

print(df.isnull().sum())
df = df.dropna()

# Count accidents by Local Government Area (LGA)
accidents_by_lga = df['National LGA Name 2017'].value_counts()

# Filter out areas with fewer accidents for better visualization
min_accidents_threshold = 10
accidents_by_lga = accidents_by_lga[accidents_by_lga >= min_accidents_threshold]

# Plotting the hotspots
plt.figure(figsize=(8, 5))
sns.barplot(x=accidents_by_lga.index, y=accidents_by_lga.values)
plt.title('Accident Hotspots by Local Government Area')
plt.xlabel('Local Government Area')
plt.ylabel('Number of Accidents')
plt.xticks(rotation=45, ha='right')
plt.show()

# Count accidents by Local Government Area (LGA)
accidents_by_lga = df['National LGA Name 2017'].value_counts()

# Filter out areas with fewer accidents for better visualization
min_accidents_threshold = 10
accidents_by_lga = accidents_by_lga[accidents_by_lga >= min_accidents_threshold]

# Create a folium map centered around Australia
m = folium.Map(location=[-25.2744, 133.7751], zoom_start=4)

# Create a MarkerCluster layer for better visualization of clustered points
marker_cluster = MarkerCluster().add_to(m)

# Add markers for each LGA with the number of accidents as the marker size
for lga, accidents in accidents_by_lga.items():
    folium.CircleMarker(
        location=[-34, 135],  # Dummy location (center of Australia)
        radius=accidents / 50,  # Adjust the radius for better visibility
        popup=f'{lga}: {accidents} accidents',
        color='red',
        fill=True,
        fill_color='red',
        fill_opacity=0.5,
    ).add_to(marker_cluster)

# Display the map
m